### ISSUE TITLE
Does not compile to WASM

### ISSUE THREAD

**Issue by drewstone** [ZK-Garage/plonk#60] opened 2021-12-15 16:21 UTC
This repo is strictly pegged to `std` dependencies, unlike most other Arkworks repositories. Is anyone working on compiling this in WASM?

**Comment by bhgomes** [comment] 2021-12-15 17:16
Yes, we're working on it. We'll add a `std` feature.

**Comment by CPerezz** [comment] 2021-12-20 09:05
Indeed @drewstone it does compile for wasm targets.
See our CI passing with these jobs: https://github.com/rust-zkp/plonk/blob/master/.github/workflows/ci.yml#L42-L44

But what it does not actually compile to is `no_std` targets.

Rust can compile a lot of it's `std` lib to WASM. The problem is that there are targets that basically do not have `std`. And for those is where we have a problem. 

As said by @bhgomes we're working on that. But it's not on our top prio list for now.

**Comment by CPerezz** [comment] 2021-12-22 08:30
Closing as no comments were made. 

We can re-open if this pops up again.

**Closed as completed by CPerezz** 2021-12-22 08:30 UTC
